### ISSUE TITLE
npm packages count for author

### ISSUE THREAD

**Issue by tunnckoCore** [badgelino/server#4]
#### API Endpoint

http://isaacs.iriscouch.com/registry/_design/app/_view/browseAuthors?startkey=%5B%22tunnckocore%22%5D&endkey=%5B%22tunnckocore%22%2C%7B%7D%5D&group_level=1

`http://isaacs.iriscouch.com/registry/_design/app/_view/browseAuthors?startkey=%5B"npmUsername"%5D&endkey=%5B"npmUsername"%2C%7B%7D%5D&group_level=1`
**Notice** `npmUsername` - replace with your usename in www.npmjs.org registry
- **startkey** - url encoded array with username as string
- **endkey** - url encoded array with username and empty object
- **group_level** - number/integer

**group_level=1** - count of published npm packages for author

``` json
{
  "rows": [
    {"key": ["tunnckocore"], "value":21}
  ]
}
```

**group_level=2** - list of author's npm packages

``` json
{
  "rows": [
    {"key":["tunnckocore","koa-better-body"],"value":1},
    {"key":["tunnckocore","koa-better-ratelimit"],"value":1},
    {"key":["tunnckocore","npmls"],"value":1},
    // ...
    {"key":["tunnckocore","gitcreate"],"value":1},
    {"key":["tunnckocore","gitclone"],"value":1},
    {"key":["tunnckocore","catchy"],"value":1},
  ]
}
```

**group_level=3** - list of author's npm packages (same as above) with description for package

**Comment by tunnckoCore** [comment]
@jonathanong more info about available query keys?
I notice also that my packages are 31, it shows 21. Your packages are 458, it shows 436. Idea?

Is it good idea to create few modules - `npm-apc` (author packages count), `npm-packages-list` depending on this?

Another way for doing this?

**Comment by tunnckoCore** [comment]
https://github.com/tunnckoCore/npm-pkgs
https://github.com/tunnckoCore/npm-pkgs-cli
https://github.com/tunnckoCore/npm-pkgs-count
https://github.com/tunnckoCore/npm-pkgs-filter

lol

**Comment by jonathanong** [comment]
No idea how any of the npm Apis worj

**Comment by tunnckoCore** [comment]
@jonathanong yep, that's too old issue.
